# permissions for end users to edit dynamicnamespaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dynamicnamespace-editor-role
rules:
- apiGroups:
  - platform.cloudnative.space
  resources:
  - dynamicnamespaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.cloudnative.space
  resources:
  - dynamicnamespaces/status
  verbs:
  - get
